import React, { useContext, useState } from 'react';
import '../../styles/sidenav/sidenav.css'
import { CardContext } from '../../context/cardContext';
// import FormCardType from './FormCardType';
import Select from 'react-select'


function Sidenav() {
  const [formData, setFormData] = useState({
    name: '',
    cardTypes: []
  })
  const { cards, setCards } = useContext(CardContext)

  const handleChange = (e) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value
    })
  }

  const handleCardTypesChange = (data) => {
    setFormData({
      ...formData,
      cardTypes: data
    })
  }

  // console.log(formData)

  const searchCards = (e) => {
    e.preventDefault(e)
    const { name, cardTypes } = formData

    const cardTypeValues = cardTypes.map(cardType => cardType.value)
    let url = `https://api.scryfall.com/cards/search?q=${name}}`

    // switch (name === '') {
    //   case name === '' && cardTypes.length > 0:
    //     url = `https://api.scryfall.com/cards/search?q=t:${cardTypeValues.join('&t:')}}`

    // }

    if (name.length === 0 && cardTypes.length > 0) {
      // url = `https://api.scryfall.com/cards/search?q=t:${cardTypeValues.join('+t:')}}`
      url = `https://api.scryfall.com/cards/search?q=t:${cardTypeValues.join('+t:')}`
    } else if (name.length > 0 && cardTypes.length > 0) {
      url = `https://api.scryfall.com/cards/search?q=${name}+t:${cardTypeValues.join('+t:')}`
    }
    
    else {
      url = `https://api.scryfall.com/cards/search?q=${name}`
    }

    fetch(url)
      .then(r => r.json())
      .then(result => setCards(result.data))
  }


  const options = [
    { value: 'battle', label: 'Battle' },
    { value: 'conspiracy', label: 'Conspiracy' },
    { value: 'creature', label: 'Creature' },
    { value: 'emblem', label: 'Emblem' },
    { value: 'enchantment', label: 'Enchantment' },
    { value: 'hero', label: 'Hero' },
    { value: 'instant', label: 'Instant' },
    { value: 'land', label: 'Land' },
    { value: 'phenomenon', label: 'Phenomenon' },
    { value: 'plane', label: 'Plane' },
    { value: 'planeswalker', label: 'Planeswalker' },
    { value: 'scheme', label: 'Scheme' },
    { value: 'sorcery', label: 'Sorcery' },
    { value: 'tribal', label: 'Tribal' },
    { value: 'vanguard', label: 'Vanguard' },
    { value: '', label: '' },
    { value: 'elite', label: 'Elite' },
    { value: 'legendary', label: 'Legendary' },
    { value: 'ongoing', label: 'Ongoing' },
    { value: 'snow', label: 'Snow' },
    { value: 'token', label: 'Token' },
    { value: 'world', label: 'World' },
    { value: '', label: '' },
    { value: 'blood', label: 'Blood' },
    { value: 'clue', label: 'Clue' },
    { value: 'contraption', label: 'Contraption' },
    { value: 'equipment', label: 'Equipment' },
    { value: 'food', label: 'Food' },
    { value: 'fortification', label: 'Fortification' },
    { value: 'gold', label: 'Gold' },
    { value: 'powerstone', label: 'Powerstone' },
    { value: 'treasure', label: 'Treasure' },
    { value: 'vehicle', label: 'Vehicle' },
    { value: '', label: '' },
    { value: 'background', label: 'Background' },
    { value: 'cartouche', label: 'Cartouche' },
    { value: 'class', label: 'Class' },
    { value: 'curse', label: 'Curse' },
    { value: 'rune', label: 'Rune' },
    { value: 'saga', label: 'Saga' },
    { value: 'shard', label: 'Shard' },
    { value: 'shrine', label: 'Shrine' },
    { value: '', label: '' },
    { value: 'desert', label: 'Desert' },
    { value: 'forest', label: 'Forest' },
    { value: 'gate', label: 'Gate' },
    { value: 'island', label: 'Island' },
    { value: 'lair', label: 'Lair' },
    { value: 'locus', label: 'Locus' },
    { value: 'mine', label: 'Mine' },
    { value: 'mountain', label: 'Mountain' },
    { value: 'sphere', label: 'Sphere' },
    { value: 'plains', label: 'Plains' },
    { value: 'power-plant', label: 'Power-Plant' },
    { value: 'swamp', label: 'Swamp' },
    { value: 'tower', label: 'Tower' },
    { value: 'urza\'s', label: 'Urza\'s' },
    { value: '', label: '' },
    { value: 'arcane', label: 'Arcane' },
    { value: 'lesson', label: 'Lesson' },
    { value: 'trap', label: 'Trap' },
    { value: '', label: '' },
    { value: 'ajani', label: 'Ajani' },
    { value: 'aminatou', label: 'Aminatou' },
    { value: 'angrath', label: 'Angrath' },
    { value: 'arlinn', label: 'Arlinn' },
    { value: 'ashiok', label: 'Ashiok' },
    { value: 'b.o.b.', label: 'B.O.B.' },
    { value: 'bahamut', label: 'Bahamut' },
    { value: 'basri', label: 'Basri' },
    { value: 'bolas', label: 'Bolas' },
    { value: 'calix', label: 'Calix' },
    { value: 'chandra', label: 'Chandra' },
    { value: 'comet', label: 'Comet' },
    { value: 'dack', label: 'Dack' },
    { value: 'dakkon', label: 'Dakkon' },
    { value: 'daretti', label: 'Daretti' },
    { value: 'davriel', label: 'Davriel' },
    { value: 'dihada', label: 'Dihada' },
    { value: 'domri', label: 'Domri' },
    { value: 'dovin', label: 'Dovin' },
    { value: 'duck', label: 'Duck' },
    { value: 'dungeon', label: 'Dungeon' },
    { value: 'ellywick', label: 'Ellywick' },
    { value: 'elminster', label: 'Elminster' },
    { value: 'elspeth', label: 'Elspeth' },
    { value: 'ersta', label: 'Ersta' },
    { value: 'estrid', label: 'Estrid' },
    { value: 'freyalise', label: 'Freyalise' },
    { value: 'garruk', label: 'Garruk' },
    { value: 'gideon', label: 'Gideon' },
    { value: 'grist', label: 'Grist' },
    { value: 'guff', label: 'Guff' },
    { value: 'huatli', label: 'Huatli' },
    { value: 'inzerva', label: 'Inzerva' },
    { value: 'jace', label: 'Jace' },
    { value: 'jared', label: 'Jared' },
    { value: 'jaya', label: 'Jaya' },
    { value: 'jeska', label: 'Jeska' },
    { value: 'kaito', label: 'Kaito' },
    { value: 'karn', label: 'Karn' },
    { value: 'kasmina', label: 'Kasmina' },
    { value: 'kaya', label: 'Kaya' },
    { value: 'kiora', label: 'Kiora' },
    { value: 'koth', label: 'Koth' },
    { value: 'liliana', label: 'Liliana' },
    { value: 'lolth', label: 'Lolth' },
    { value: 'lukka', label: 'Lukka' },
    { value: 'master', label: 'Master' },
    { value: 'minsc', label: 'Minsc' },
    { value: 'mordenkainen', label: 'Mordenkainen' },
    { value: 'nahiri', label: 'Nahiri' },
    { value: 'narset', label: 'Narset' },
    { value: 'niko', label: 'Niko' },
    { value: 'nissa', label: 'Nissa' },
    { value: 'nixilis', label: 'Nixilis' },
    { value: 'oko', label: 'Oko' },
    { value: 'ral', label: 'Ral' },
    { value: 'rowan', label: 'Rowan' },
    { value: 'saheeli', label: 'Saheeli' },
    { value: 'samut', label: 'Samut' },
    { value: 'sarkhan', label: 'Sarkhan' },
    { value: 'serra', label: 'Serra' },
    { value: 'sivitri', label: 'Sivitri' },
    { value: 'sorin', label: 'Sorin' },
    { value: 'szat', label: 'Szat' },
    { value: 'tamiyo', label: 'Tamiyo' },
    { value: 'tasha', label: 'Tasha' },
    { value: 'teferi', label: 'Teferi' },
    { value: 'teyo', label: 'Teyo' },
    { value: 'tezzeret', label: 'Tezzeret' },
    { value: 'tibalt', label: 'Tibalt' },
    { value: 'tyvar', label: 'Tyvar' },
    { value: 'ugin', label: 'Ugin' },
    { value: 'urza', label: 'Urza' },
    { value: 'venser', label: 'Venser' },
    { value: 'vivien', label: 'Vivien' },
    { value: 'vraska', label: 'Vraska' },
    { value: 'will', label: 'Will' },
    { value: 'windgrace', label: 'Windgrace' },
    { value: 'wrenn', label: 'Wrenn' },
    { value: 'xenagos', label: 'Xenagos' },
    { value: 'yanggu', label: 'Yanggu' },
    { value: 'yanling', label: 'Yanling' },
    { value: 'zariel', label: 'Zariel' },
    { value: '', label: '' },
    { value: 'aetherborn', label: 'Aetherborn' },
    { value: 'alicorn', label: 'Alicorn' },
    { value: 'alien', label: 'Alien' },
    { value: 'ally', label: 'Ally' },
    { value: 'angel', label: 'Angel' },
    { value: 'antelope', label: 'Antelope' },
    { value: 'ape', label: 'Ape' },
    { value: 'archer', label: 'Archer' },
    { value: 'archon', label: 'Archon' },
    { value: 'army', label: 'Army' },
    { value: 'art', label: 'Art' },
    { value: 'artificer', label: 'Artificer' },
    { value: 'assassin', label: 'Assassin' },
    { value: 'assembly-worker', label: 'Assembly-Worker' },
    { value: 'astartes', label: 'Astartes' },
    { value: 'atog', label: 'Atog' },
    { value: 'aurochs', label: 'Aurochs' },
    { value: 'autobot', label: 'Autobot' },
    { value: 'avatar', label: 'Avatar' },
    { value: 'azra', label: 'Azra' },
    { value: 'baddest,', label: 'Baddest,' },
    { value: 'badger', label: 'Badger' },
    { value: 'balloon', label: 'Balloon' },
    { value: 'barbarian', label: 'Barbarian' },
    { value: 'bard', label: 'Bard' },
    { value: 'basilisk', label: 'Basilisk' },
    { value: 'bat', label: 'Bat' },
    { value: 'bear', label: 'Bear' },
    { value: 'beast', label: 'Beast' },
    { value: 'beaver', label: 'Beaver' },
    { value: 'beeble', label: 'Beeble' },
    { value: 'beholder', label: 'Beholder' },
    { value: 'berserker', label: 'Berserker' },
    { value: 'biggest,', label: 'Biggest,' },
    { value: 'bird', label: 'Bird' },
    { value: 'blinkmoth', label: 'Blinkmoth' },
    { value: 'boar', label: 'Boar' },
    { value: 'brainiac', label: 'Brainiac' },
    { value: 'bringer', label: 'Bringer' },
    { value: 'brushwagg', label: 'Brushwagg' },
    { value: 'bureaucrat', label: 'Bureaucrat' },
    { value: 'c\'tan', label: 'C\'tan' },
    { value: 'camarid', label: 'Camarid' },
    { value: 'camel', label: 'Camel' },
    { value: 'caribou', label: 'Caribou' },
    { value: 'carrier', label: 'Carrier' },
    { value: 'cat', label: 'Cat' },
    { value: 'centaur', label: 'Centaur' },
    { value: 'cephalid', label: 'Cephalid' },
    { value: 'chameleon', label: 'Chameleon' },
    { value: 'chicken', label: 'Chicken' },
    { value: 'child', label: 'Child' },
    { value: 'chimera', label: 'Chimera' },
    { value: 'citizen', label: 'Citizen' },
    { value: 'clamfolk', label: 'Clamfolk' },
    { value: 'cleric', label: 'Cleric' },
    { value: 'clown', label: 'Clown' },
    { value: 'cockatrice', label: 'Cockatrice' },
    { value: 'construct', label: 'Construct' },
    { value: 'cow', label: 'Cow' },
    { value: 'coward', label: 'Coward' },
    { value: 'crab', label: 'Crab' },
    { value: 'crocodile', label: 'Crocodile' },
    { value: 'custodes', label: 'Custodes' },
    { value: 'cyborg', label: 'Cyborg' },
    { value: 'cyclops', label: 'Cyclops' },
    { value: 'dauthi', label: 'Dauthi' },
    { value: 'deer', label: 'Deer' },
    { value: 'demigod', label: 'Demigod' },
    { value: 'demon', label: 'Demon' },
    { value: 'deserter', label: 'Deserter' },
    { value: 'designer', label: 'Designer' },
    { value: 'devil', label: 'Devil' },
    { value: 'dinosaur', label: 'Dinosaur' },
    { value: 'djinn', label: 'Djinn' },
    { value: 'dog', label: 'Dog' },
    { value: 'donkey', label: 'Donkey' },
    { value: 'dragon', label: 'Dragon' },
    { value: 'drake', label: 'Drake' },
    { value: 'dreadnought', label: 'Dreadnought' },
    { value: 'drone', label: 'Drone' },
    { value: 'druid', label: 'Druid' },
    { value: 'dryad', label: 'Dryad' },
    { value: 'dwarf', label: 'Dwarf' },
    { value: 'efreet', label: 'Efreet' },
    { value: 'egg', label: 'Egg' },
    { value: 'elder', label: 'Elder' },
    { value: 'eldrazi', label: 'Eldrazi' },
    { value: 'elemental', label: 'Elemental' },
    { value: 'elemental?', label: 'Elemental?' },
    { value: 'elephant', label: 'Elephant' },
    { value: 'elf', label: 'Elf' },
    { value: 'elk', label: 'Elk' },
    { value: 'elves', label: 'Elves' },
    { value: 'employee', label: 'Employee' },
    { value: 'etiquette', label: 'Etiquette' },
    { value: 'eye', label: 'Eye' },
    { value: 'faerie', label: 'Faerie' },
    { value: 'ferret', label: 'Ferret' },
    { value: 'fish', label: 'Fish' },
    { value: 'flagbearer', label: 'Flagbearer' },
    { value: 'fox', label: 'Fox' },
    { value: 'fractal', label: 'Fractal' },
    { value: 'frog', label: 'Frog' },
    { value: 'fungus', label: 'Fungus' },
    { value: 'gamer', label: 'Gamer' },
    { value: 'gargoyle', label: 'Gargoyle' },
    { value: 'germ', label: 'Germ' },
    { value: 'giant', label: 'Giant' },
    { value: 'gith', label: 'Gith' },
    { value: 'gnoll', label: 'Gnoll' },
    { value: 'gnome', label: 'Gnome' },
    { value: 'goat', label: 'Goat' },
    { value: 'goblin', label: 'Goblin' },
    { value: 'god', label: 'God' },
    { value: 'golem', label: 'Golem' },
    { value: 'gorgon', label: 'Gorgon' },
    { value: 'grandchild', label: 'Grandchild' },
    { value: 'graveborn', label: 'Graveborn' },
    { value: 'gremlin', label: 'Gremlin' },
    { value: 'griffin', label: 'Griffin' },
    { value: 'guest', label: 'Guest' },
    { value: 'gus', label: 'Gus' },
    { value: 'hag', label: 'Hag' },
    { value: 'halfling', label: 'Halfling' },
    { value: 'hamster', label: 'Hamster' },
    { value: 'harpy', label: 'Harpy' },
    { value: 'hatificer', label: 'Hatificer' },
    { value: 'head', label: 'Head' },
    { value: 'hellion', label: 'Hellion' },
    { value: 'hero', label: 'Hero' },
    { value: 'hippo', label: 'Hippo' },
    { value: 'hippogriff', label: 'Hippogriff' },
    { value: 'homarid', label: 'Homarid' },
    { value: 'homunculus', label: 'Homunculus' },
    { value: 'hornet', label: 'Hornet' },
    { value: 'horror', label: 'Horror' },
    { value: 'horse', label: 'Horse' },
    { value: 'human', label: 'Human' },
    { value: 'hydra', label: 'Hydra' },
    { value: 'hyena', label: 'Hyena' },
    { value: 'illusion', label: 'Illusion' },
    { value: 'imp', label: 'Imp' },
    { value: 'incarnation', label: 'Incarnation' },
    { value: 'inkling', label: 'Inkling' },
    { value: 'inquisitor', label: 'Inquisitor' },
    { value: 'insect', label: 'Insect' },
    { value: 'jackal', label: 'Jackal' },
    { value: 'jellyfish', label: 'Jellyfish' },
    { value: 'juggernaut', label: 'Juggernaut' },
    { value: 'kangaroo', label: 'Kangaroo' },
    { value: 'kavu', label: 'Kavu' },
    { value: 'killbot', label: 'Killbot' },
    { value: 'kirin', label: 'Kirin' },
    { value: 'kithkin', label: 'Kithkin' },
    { value: 'knight', label: 'Knight' },
    { value: 'kobold', label: 'Kobold' },
    { value: 'kor', label: 'Kor' },
    { value: 'kraken', label: 'Kraken' },
    { value: 'lady', label: 'Lady' },
    { value: 'lamia', label: 'Lamia' },
    { value: 'lammasu', label: 'Lammasu' },
    { value: 'leech', label: 'Leech' },
    { value: 'leviathan', label: 'Leviathan' },
    { value: 'lhurgoyf', label: 'Lhurgoyf' },
    { value: 'licid', label: 'Licid' },
    { value: 'lizard', label: 'Lizard' },
    { value: 'lobster', label: 'Lobster' },
    { value: 'mammoth', label: 'Mammoth' },
    { value: 'manticore', label: 'Manticore' },
    { value: 'masticore', label: 'Masticore' },
    { value: 'mercenary', label: 'Mercenary' },
    { value: 'merfolk', label: 'Merfolk' },
    { value: 'metathran', label: 'Metathran' },
    { value: 'mime', label: 'Mime' },
    { value: 'minion', label: 'Minion' },
    { value: 'minotaur', label: 'Minotaur' },
    { value: 'mite', label: 'Mite' },
    { value: 'mole', label: 'Mole' },
    { value: 'monger', label: 'Monger' },
    { value: 'mongoose', label: 'Mongoose' },
    { value: 'monk', label: 'Monk' },
    { value: 'monkey', label: 'Monkey' },
    { value: 'moonfolk', label: 'Moonfolk' },
    { value: 'mouse', label: 'Mouse' },
    { value: 'mummy', label: 'Mummy' },
    { value: 'mutant', label: 'Mutant' },
    { value: 'myr', label: 'Myr' },
    { value: 'mystic', label: 'Mystic' },
    { value: 'naga', label: 'Naga' },
    { value: 'nastiest,', label: 'Nastiest,' },
    { value: 'nautilus', label: 'Nautilus' },
    { value: 'necron', label: 'Necron' },
    { value: 'nephilim', label: 'Nephilim' },
    { value: 'nightmare', label: 'Nightmare' },
    { value: 'nightstalker', label: 'Nightstalker' },
    { value: 'ninja', label: 'Ninja' },
    { value: 'noble', label: 'Noble' },
    { value: 'noggle', label: 'Noggle' },
    { value: 'nomad', label: 'Nomad' },
    { value: 'nymph', label: 'Nymph' },
    { value: 'octopus', label: 'Octopus' },
    { value: 'ogre', label: 'Ogre' },
    { value: 'ooze', label: 'Ooze' },
    { value: 'orb', label: 'Orb' },
    { value: 'orc', label: 'Orc' },
    { value: 'orgg', label: 'Orgg' },
    { value: 'otter', label: 'Otter' },
    { value: 'ouphe', label: 'Ouphe' },
    { value: 'ox', label: 'Ox' },
    { value: 'oyster', label: 'Oyster' },
    { value: 'pangolin', label: 'Pangolin' },
    { value: 'paratrooper', label: 'Paratrooper' },
    { value: 'peasant', label: 'Peasant' },
    { value: 'pegasus', label: 'Pegasus' },
    { value: 'pentavite', label: 'Pentavite' },
    { value: 'performer', label: 'Performer' },
    { value: 'pest', label: 'Pest' },
    { value: 'phelddagrif', label: 'Phelddagrif' },
    { value: 'phoenix', label: 'Phoenix' },
    { value: 'phyrexian', label: 'Phyrexian' },
    { value: 'pilot', label: 'Pilot' },
    { value: 'pincher', label: 'Pincher' },
    { value: 'pirate', label: 'Pirate' },
    { value: 'plant', label: 'Plant' },
    { value: 'porcupine', label: 'Porcupine' },
    { value: 'praetor', label: 'Praetor' },
    { value: 'primarch', label: 'Primarch' },
    { value: 'prism', label: 'Prism' },
    { value: 'processor', label: 'Processor' },
    { value: 'proper', label: 'Proper' },
    { value: 'rabbit', label: 'Rabbit' },
    { value: 'raccoon', label: 'Raccoon' },
    { value: 'ranger', label: 'Ranger' },
    { value: 'rat', label: 'Rat' },
    { value: 'rebel', label: 'Rebel' },
    { value: 'reflection', label: 'Reflection' },
    { value: 'reveler', label: 'Reveler' },
    { value: 'rhino', label: 'Rhino' },
    { value: 'rigger', label: 'Rigger' },
    { value: 'robot', label: 'Robot' },
    { value: 'rogue', label: 'Rogue' },
    { value: 'sable', label: 'Sable' },
    { value: 'salamander', label: 'Salamander' },
    { value: 'samurai', label: 'Samurai' },
    { value: 'sand', label: 'Sand' },
    { value: 'saproling', label: 'Saproling' },
    { value: 'satyr', label: 'Satyr' },
    { value: 'scarecrow', label: 'Scarecrow' },
    { value: 'scientist', label: 'Scientist' },
    { value: 'scion', label: 'Scion' },
    { value: 'scorpion', label: 'Scorpion' },
    { value: 'scout', label: 'Scout' },
    { value: 'sculpture', label: 'Sculpture' },
    { value: 'serf', label: 'Serf' },
    { value: 'serpent', label: 'Serpent' },
    { value: 'servo', label: 'Servo' },
    { value: 'shade', label: 'Shade' },
    { value: 'shaman', label: 'Shaman' },
    { value: 'shapeshifter', label: 'Shapeshifter' },
    { value: 'shark', label: 'Shark' },
    { value: 'sheep', label: 'Sheep' },
    { value: 'ship', label: 'Ship' },
    { value: 'siren', label: 'Siren' },
    { value: 'skeleton', label: 'Skeleton' },
    { value: 'slith', label: 'Slith' },
    { value: 'sliver', label: 'Sliver' },
    { value: 'slug', label: 'Slug' },
    { value: 'snake', label: 'Snake' },
    { value: 'soldier', label: 'Soldier' },
    { value: 'soltari', label: 'Soltari' },
    { value: 'spawn', label: 'Spawn' },
    { value: 'specter', label: 'Specter' },
    { value: 'spellshaper', label: 'Spellshaper' },
    { value: 'sphinx', label: 'Sphinx' },
    { value: 'spider', label: 'Spider' },
    { value: 'spike', label: 'Spike' },
    { value: 'spirit', label: 'Spirit' },
    { value: 'splinter', label: 'Splinter' },
    { value: 'sponge', label: 'Sponge' },
    { value: 'spy', label: 'Spy' },
    { value: 'squid', label: 'Squid' },
    { value: 'squirrel', label: 'Squirrel' },
    { value: 'starfish', label: 'Starfish' },
    { value: 'surrakar', label: 'Surrakar' },
    { value: 'survivor', label: 'Survivor' },
    { value: 'teddy', label: 'Teddy' },
    { value: 'tentacle', label: 'Tentacle' },
    { value: 'tetravite', label: 'Tetravite' },
    { value: 'thalakos', label: 'Thalakos' },
    { value: 'the', label: 'The' },
    { value: 'thopter', label: 'Thopter' },
    { value: 'thrull', label: 'Thrull' },
    { value: 'tiefling', label: 'Tiefling' },
    { value: 'townsfolk', label: 'Townsfolk' },
    { value: 'treefolk', label: 'Treefolk' },
    { value: 'trilobite', label: 'Trilobite' },
    { value: 'triskelavite', label: 'Triskelavite' },
    { value: 'troll', label: 'Troll' },
    { value: 'turtle', label: 'Turtle' },
    { value: 'tyranid', label: 'Tyranid' },
    { value: 'unicorn', label: 'Unicorn' },
    { value: 'vampire', label: 'Vampire' },
    { value: 'vampyre', label: 'Vampyre' },
    { value: 'vedalken', label: 'Vedalken' },
    { value: 'viashino', label: 'Viashino' },
    { value: 'villain', label: 'Villain' },
    { value: 'volver', label: 'Volver' },
    { value: 'waiter', label: 'Waiter' },
    { value: 'wall', label: 'Wall' },
    { value: 'walrus', label: 'Walrus' },
    { value: 'warlock', label: 'Warlock' },
    { value: 'warrior', label: 'Warrior' },
    { value: 'wasp', label: 'Wasp' },
    { value: 'weird', label: 'Weird' },
    { value: 'werewolf', label: 'Werewolf' },
    { value: 'whale', label: 'Whale' },
    { value: 'wizard', label: 'Wizard' },
    { value: 'wolf', label: 'Wolf' },
    { value: 'wolverine', label: 'Wolverine' },
    { value: 'wombat', label: 'Wombat' },
    { value: 'worm', label: 'Worm' },
    { value: 'wraith', label: 'Wraith' },
    { value: 'wrestler', label: 'Wrestler' },
    { value: 'wurm', label: 'Wurm' },
    { value: 'yeti', label: 'Yeti' },
    { value: 'zombie', label: 'Zombie' },
    { value: 'zubera', label: 'Zubera' },
    { value: 'human', label: 'human' },
    { value: 'knight', label: 'knight' },
    { value: '', label: '' },
    { value: 'amonkhet', label: 'Amonkhet' },
    { value: 'antausia', label: 'Antausia' },
    { value: 'arcavios', label: 'Arcavios' },
    { value: 'arkhos', label: 'Arkhos' },
    { value: 'azgol', label: 'Azgol' },
    { value: 'belenon', label: 'Belenon' },
    { value: 'bolas\'s meditation realm', label: 'Bolas\'s Meditation Realm' },
    { value: 'capenna', label: 'Capenna' },
    { value: 'cridhe', label: 'Cridhe' },
    { value: 'dominaria', label: 'Dominaria' },
    { value: 'echoir', label: 'Echoir' },
    { value: 'eldraine', label: 'Eldraine' },
    { value: 'equilor', label: 'Equilor' },
    { value: 'ergamon', label: 'Ergamon' },
    { value: 'fabacin', label: 'Fabacin' },
    { value: 'fiora', label: 'Fiora' },
    { value: 'gargantikar', label: 'Gargantikar' },
    { value: 'gobakhan', label: 'Gobakhan' },
    { value: 'ikoria', label: 'Ikoria' },
    { value: 'innistrad', label: 'Innistrad' },
    { value: 'iquatana', label: 'Iquatana' },
    { value: 'ir', label: 'Ir' },
    { value: 'ixalan', label: 'Ixalan' },
    { value: 'kaladesh', label: 'Kaladesh' },
    { value: 'kaldheim', label: 'Kaldheim' },
    { value: 'kamigawa', label: 'Kamigawa' },
    { value: 'karsus', label: 'Karsus' },
    { value: 'kephalai', label: 'Kephalai' },
    { value: 'kinshala', label: 'Kinshala' },
    { value: 'kolbahan', label: 'Kolbahan' },
    { value: 'kylem', label: 'Kylem' },
    { value: 'kyneth', label: 'Kyneth' },
    { value: 'lorwyn', label: 'Lorwyn' },
    { value: 'luvion', label: 'Luvion' },
    { value: 'mercadia', label: 'Mercadia' },
    { value: 'mirrodin', label: 'Mirrodin' },
    { value: 'moag', label: 'Moag' },
    { value: 'mongseng', label: 'Mongseng' },
    { value: 'muraganda', label: 'Muraganda' },
    { value: 'new phyrexia', label: 'New Phyrexia' },
    { value: 'phyrexia', label: 'Phyrexia' },
    { value: 'pyrulea', label: 'Pyrulea' },
    { value: 'rabiah', label: 'Rabiah' },
    { value: 'rath', label: 'Rath' },
    { value: 'ravnica', label: 'Ravnica' },
    { value: 'regatha', label: 'Regatha' },
    { value: 'segovia', label: 'Segovia' },
    { value: 'serra’s realm', label: 'Serra’s Realm' },
    { value: 'shadowmoor', label: 'Shadowmoor' },
    { value: 'shandalar', label: 'Shandalar' },
    { value: 'shenmeng', label: 'Shenmeng' },
    { value: 'tarkir', label: 'Tarkir' },
    { value: 'the abyss', label: 'The Abyss' },
    { value: 'the library', label: 'The Library' },
    { value: 'theros', label: 'Theros' },
    { value: 'ulgrotha', label: 'Ulgrotha' },
    { value: 'valla', label: 'Valla' },
    { value: 'vryn', label: 'Vryn' },
    { value: 'wildfire', label: 'Wildfire' },
    { value: 'xerex', label: 'Xerex' },
    { value: 'zendikar', label: 'Zendikar' },
    { value: 'zhalfir', label: 'Zhalfir' }
  ]

  return (
    <div>
      <div className="sidenav">
        <form className='filter-form' onSubmit={searchCards}>
          <label>Name:</label>
          <input
            name='name'
            type='text'
            placeholder='Type anything...'
            onChange={handleChange}
            value={formData.name}
          />

          <label>Type:</label>
          {/* <FormCardType onUpdateCardType={handleChange} setFormData={setFormData} formData={formData}/> */}
          <Select options={options} name='cardTypes' onChange={handleCardTypesChange} isMulti />


          <div className='filters-button'>
            <button type='submit'>Search</button>
          </div>
        </form>
      </div>
    </div>
  );
}

export default Sidenav;
