import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="bg-gray-800 p-5 text-xl text-white">
          <Link href='/' className='m-5'>Home</Link>
          <Link href='/browse' className='m-5'>Browse</Link>
        </nav>

        {children}
      </body>
    </html>
  )
}
